#!/usr/bin/env bash
# Name of private key 
filename_key="school"

# Number of bit
bit_num="4096"

# name of passphase
passphrase="betty"

# Create the RSA key pair with 4096 bits and protect it with the passphrase
ssh-keygen -t rsa -b $bit_num -f $filename_key -N "$passphrase"

# Display success message 
echo "RSA key pair created successfully."
