#!/usr/bin/env bash
#transfer file to severs

if [$# - lt 4]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
#parameters
file="$1"
host="$2"
username="$3"
ssh_key="$4"

#transfer the data
scp -o "StrictHostKeyChecking=no" -i "$ssh_key" "$file" "$username"@"$host":~

exit 0
